[build-system]
requires = [
    "uv_build >= 0.12.5, <0.13.0",
    "psycopg[binary]",
    "orjson"
    ]
build-backend = "uv_build"

[project]
name = "drifTech-lib"
version = "0.5.11"
authors = [{name = "driftbluestone", email = "driftbluestone@gmail.com"}]
description = "Common files/functions across most drifTech software"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Source = "https://github.com/driftbluestone/drifTech-lib"